/**
 * Components: every components/{name}/scripts.ts. Each registers itself with
 * define() on import. Import this from the main script entry: import './components';
 *
 * Generated by tools/component-index.js from the folders in components/.
 * Don't edit it: add or delete a component folder instead.
 */

import './site-header/scripts';
