/**
 * Write components/index.css and components/index.ts from the component
 * folders, so adding or deleting a folder is all it takes:
 *
 *   components/site-header/styles.css   →  @import "./site-header/styles.css";
 *   components/site-header/scripts.ts   →  import './site-header/scripts';
 *
 * Vite (and Astro, SvelteKit, Nuxt): add the plugin. It writes both files
 * when the dev server starts or a build begins, and again whenever a
 * component's styles.css or scripts.ts is added or deleted.
 *
 *   // vite.config.js
 *   import { componentIndex } from './tools/component-index.js';
 *   export default { plugins: [componentIndex()] };
 *
 * Other builds: run it before building, e.g. as a prebuild script:
 *
 *   node tools/component-index.js [components-dir]
 *
 * Why not a glob @import: Vite and postcss-import both inline imports before
 * a PostCSS plugin could expand a glob, and import.meta.glob is Vite-only.
 * Generated files work in every build.
 *
 * Commit both files, so a fresh clone builds before this has run. A file is
 * only written when its content changes, so file watchers don't loop.
 *
 * Plain ESM with JSDoc so it can be copied into any build.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const NOTE = [
    ' * Generated by tools/component-index.js from the folders in components/.',
    " * Don't edit it: add or delete a component folder instead.",
];

/**
 * Component folders that have styles, and those that have a script, sorted by name.
 * @param {string} dir - The components folder.
 * @returns {{ styles: string[], scripts: string[] }}
 */
export function findComponents(dir) {
    const names = readdirSync(dir, { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name)
        .sort();

    return {
        styles: names.filter((name) => existsSync(join(dir, name, 'styles.css'))),
        scripts: names.filter((name) => existsSync(join(dir, name, 'scripts.ts'))),
    };
}

/**
 * The two index files' contents.
 * @param {{ styles: string[], scripts: string[] }} components
 * @returns {{ css: string, ts: string }}
 */
export function renderIndex({ styles, scripts }) {
    const css = [
        '/* ---------------------------------------------------------------------------',
        ' * Components: every components/{name}/styles.css. Imported by css/index.css.',
        ' *',
        ...NOTE,
        ' * ------------------------------------------------------------------------- */',
        '',
        ...styles.map((name) => `@import "./${name}/styles.css";`),
        '',
    ].join('\n');

    const ts = [
        '/**',
        ' * Components: every components/{name}/scripts.ts. Each registers itself with',
        " * define() on import. Import this from the main script entry: import './components';",
        ' *',
        ...NOTE,
        ' */',
        '',
        ...(scripts.length ? scripts.map((name) => `import './${name}/scripts';`) : ['export {};']),
        '',
    ].join('\n');

    return { css, ts };
}

/**
 * @param {string} path
 * @param {string} content
 * @returns {boolean} Whether the file changed.
 */
function writeIfChanged(path, content) {
    if (existsSync(path) && readFileSync(path, 'utf8') === content) return false;
    writeFileSync(path, content);
    return true;
}

/**
 * Write index.css and index.ts into the components folder.
 * @param {string} [dir] - The components folder. Defaults to ./components.
 * @returns {boolean} Whether either file changed.
 */
export function writeComponentIndex(dir = 'components') {
    const { css, ts } = renderIndex(findComponents(dir));
    const cssChanged = writeIfChanged(join(dir, 'index.css'), css);
    const tsChanged = writeIfChanged(join(dir, 'index.ts'), ts);
    return cssChanged || tsChanged;
}

/**
 * Vite plugin: keep the index files in step with the component folders.
 * @param {{ dir?: string }} [options] - dir: the components folder, absolute or from the working directory.
 * @returns {import('vite').Plugin}
 */
export function componentIndex(options = {}) {
    const dir = resolve(options.dir ?? 'components');
    const componentFile = /[\\/](styles\.css|scripts\.ts)$/;

    return {
        name: 'struts-component-index',
        buildStart() {
            writeComponentIndex(dir);
        },
        configureServer(server) {
            server.watcher.add(dir);
            /** @param {string} file */
            const update = (file) => {
                if (file.startsWith(dir) && componentFile.test(file)) writeComponentIndex(dir);
            };
            server.watcher.on('add', update);
            server.watcher.on('unlink', update);
        },
    };
}

// Run directly: node tools/component-index.js [dir]
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    writeComponentIndex(process.argv[2]);
}

export default componentIndex;
