/**
 * Write components/index.css and components/index.ts from the component
 * folders, so adding or deleting a folder is all it takes:
 *
 *   components/site-header/styles.css   →  @import "./site-header/styles.css";
 *   components/site-header/scripts.ts   →  import './site-header/scripts';
 *
 * Vite (and Astro, SvelteKit, Nuxt): add the plugin. It writes both files
 * when the dev server starts or a build begins, and again whenever a
 * component's styles.css or scripts.ts is added or deleted.
 *
 *   // vite.config.js
 *   import { componentIndex } from './tools/component-index.js';
 *   export default { plugins: [componentIndex()] };
 *
 * Other builds: run it before building, e.g. as a prebuild script:
 *
 *   node tools/component-index.js [components-dir] [--js]
 *
 * Projects without TypeScript keep compiled scripts.js files instead: pass
 * --js (or { language: 'js' }) to look for those and write index.js.
 *
 * Why not a glob @import: Vite and postcss-import both inline imports before
 * a PostCSS plugin could expand a glob, and import.meta.glob is Vite-only.
 * Generated files work in every build.
 *
 * Commit both files, so a fresh clone builds before this has run. A file is
 * only written when its content changes, so file watchers don't loop.
 *
 * Plain ESM with JSDoc so it can be copied into any build.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const NOTE = [
    ' * Generated by tools/component-index.js from the folders in components/.',
    " * Don't edit it: add or delete a component folder instead.",
];

/** @typedef {'ts' | 'js'} Language */

/**
 * Component folders that have styles, and those that have a script, sorted by name.
 * @param {string} dir - The components folder.
 * @param {Language} [language] - Look for scripts.ts or scripts.js.
 * @returns {{ styles: string[], scripts: string[] }}
 */
export function findComponents(dir, language = 'ts') {
    const names = readdirSync(dir, { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name)
        .sort();

    return {
        styles: names.filter((name) => existsSync(join(dir, name, 'styles.css'))),
        scripts: names.filter((name) => existsSync(join(dir, name, `scripts.${language}`))),
    };
}

/**
 * The two index files' contents.
 * @param {{ styles: string[], scripts: string[] }} components
 * @param {Language} [language]
 * @returns {{ css: string, script: string }}
 */
export function renderIndex({ styles, scripts }, language = 'ts') {
    const css = [
        '/* ---------------------------------------------------------------------------',
        ' * Components: every components/{name}/styles.css. Imported by css/index.css.',
        ' *',
        ...NOTE,
        ' * ------------------------------------------------------------------------- */',
        '',
        ...styles.map((name) => `@import "./${name}/styles.css";`),
        '',
    ].join('\n');

    const script = [
        '/**',
        ` * Components: every components/{name}/scripts.${language}. Each registers itself with`,
        " * define() on import. Import this from the main script entry: import './components';",
        ' *',
        ...NOTE,
        ' */',
        '',
        ...(scripts.length ? scripts.map((name) => `import './${name}/scripts';`) : ['export {};']),
        '',
    ].join('\n');

    return { css, script };
}

/**
 * @param {string} path
 * @param {string} content
 * @returns {boolean} Whether the file changed.
 */
function writeIfChanged(path, content) {
    if (existsSync(path) && readFileSync(path, 'utf8') === content) return false;
    writeFileSync(path, content);
    return true;
}

/**
 * Write index.css and index.ts (or index.js) into the components folder.
 * @param {string} [dir] - The components folder. Defaults to ./components.
 * @param {{ language?: Language }} [options]
 * @returns {boolean} Whether either file changed.
 */
export function writeComponentIndex(dir = 'components', { language = 'ts' } = {}) {
    const { css, script } = renderIndex(findComponents(dir, language), language);
    const cssChanged = writeIfChanged(join(dir, 'index.css'), css);
    const scriptChanged = writeIfChanged(join(dir, `index.${language}`), script);
    return cssChanged || scriptChanged;
}

/**
 * Vite plugin: keep the index files in step with the component folders.
 * @param {{ dir?: string, language?: Language }} [options] - dir: the components folder,
 *   absolute or from the working directory. language: 'js' for scripts.js and index.js.
 * @returns {import('vite').Plugin}
 */
export function componentIndex(options = {}) {
    const dir = resolve(options.dir ?? 'components');
    const language = options.language ?? 'ts';
    const componentFile = /[\\/](styles\.css|scripts\.[jt]s)$/;

    return {
        name: 'struts-component-index',
        buildStart() {
            writeComponentIndex(dir, { language });
        },
        configureServer(server) {
            server.watcher.add(dir);
            /** @param {string} file */
            const update = (file) => {
                if (file.startsWith(dir) && componentFile.test(file)) writeComponentIndex(dir, { language });
            };
            server.watcher.on('add', update);
            server.watcher.on('unlink', update);
        },
    };
}

// Run directly: node tools/component-index.js [dir] [--js]
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    const args = process.argv.slice(2);
    const dir = args.find((arg) => !arg.startsWith('--'));
    writeComponentIndex(dir, { language: args.includes('--js') ? 'js' : 'ts' });
}

export default componentIndex;
